spring.application.name=user-service

server.port=1000

#DB properties

spring.datasource.url=jdbc:postgresql://localhost:5432/usersdb

spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#eureka server

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

