spring.application.name=auth-srvice

server.port=8085

# User Service URL
user.service.url=http://localhost:1000

# JWT Secret Key (minimum 32 characters)
jwt.secret=12345678901234567890123456789012

# Token Expiry (24 Hours)
jwt.expiration=86400000

# Config Server
spring.config.import=configserver:http://localhost:8888