spring.application.name=payment-service
spring.config.import=configserver:http://localhost:8888


#server.port=1003

#spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.properties.hibernate.default_schema=public
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=payment-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#
##eureka server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
